### ISSUE TITLE
install electron-windows-notifications error

### ISSUE THREAD

**Issue by boyphongsakorn** [felixrieseberg/electron-windows-notifications#33]
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 1
npm ERR! path D:\fpsmember\node_modules\@nodert-win10-au\windows.foundation
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR!   _nodert_generated.cpp
npm ERR! d:\fpsmember\node_modules\@nodert-win10-au\windows.foundation\_nodert_generated.cpp : fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\fpsmember\node_modules\@nodert-win10-au\windows.foundation\build\binding.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.3 found at "C:\Python38\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1177) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python38\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\boy15\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\fpsmember\\node_modules\\@nodert-win10-au\\windows.foundation\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\fpsmember\\node_modules\\@nodert-win10-au\\windows.foundation\\common.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\boy15\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\boy15\\AppData\\Local\\node-gyp\\Cache\\14.17.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\boy15\\AppData\\Local\\node-gyp\\Cache\\14.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\boy15\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\boy15\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.17.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\fpsmember\\node_modules\\@nodert-win10-au\\windows.foundation',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\fpsmember\\node_modules\\@nodert-win10-au\\windows.foundation\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\boy15\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "P:\\nodejs\\node.exe" "C:\\Users\\boy15\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\fpsmember\node_modules\@nodert-win10-au\windows.foundation
npm ERR! gyp ERR! node -v v14.17.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\boy15\AppData\Local\npm-cache\_logs\2021-06-12T14_41_46_318Z-debug.log

**Comment by treckstar** [comment]
Was having this exact same error on my Windows 10, using Cmder terminal. I found a lot of information from #20, [specifically this message.](https://github.com/felixrieseberg/electron-windows-notifications/issues/20#issuecomment-647095227)

#### To put it all together, I did the following:
- `npm config set msvs_version 2017` (I only have VS 2017 installed, so this may not apply to some)
- `npm install -g node-gyp` (this surprisingly went with no errors)
- Installed the latest version of [Python from Microsoft store.](https://www.microsoft.com/en-us/p/python-310/9pjpw5ldxlz5)
- Installed Windows 10 SDK (10.0.15063.468) and was able to [download it here]: (https://go.microsoft.com/fwlink/p/?LinkId=845298)

#### Lastly, I copied these two files:
- `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x86\store\references\platform.winmd`
- `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17763.0\Windows.winmd`

#### To this folder, (that I had to create part of):
- `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\store\references`
_The folder paths above may vary depending on your system configuration, so check in the NodeRT solution for a build/binding project file._

At this point I was then able to finally run `npm install --save electron-windows-notifications`

Hopefully this helps someone... any time node-gyp pops up I always expect a headache. This time I was surprised it went somewhat painlessly.
