### ISSUE TITLE
Close notifications manually

### ISSUE THREAD

**Issue by clusterberries** [felixrieseberg/electron-windows-notifications#8]
Hi!
Currently ToastNotifications are displayed for ~6 seconds and then disappear (windows 10). I tried to set `expirationTime`, but it affects only notification inside action center. Is there a chance to set a timer or display notification till it will be closed manually by clicking or calling `notification.hide()`?

**Comment by clusterberries** [comment]
After investigation of Windows documentation (it is very ununderstandable :( ) I found out that there are only two ways how to display notifications: short (~5s) and long (~25s).
See details here
https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/element-toast
https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh779727(v=win.10)

@felixrieseberg if you can confirm that there is no another way how to set notification display time, the issue can be closed.

**Comment by clusterberries** [comment]
Oh, I also found 'scenario="reminder"' property... It seems to solve my problem. I hate Windows documentation :)

**Comment by saurabh21289** [comment]
> Oh, I also found 'scenario="reminder"' property... It seems to solve my problem. I hate Windows documentation :)

Does this also allow the notification to persist in the Action Center if the user does not interact with it for more than 5 or 25 seconds?

**Comment by clusterberries** [comment]
No, it is a separate Windows 10 setting. User can set manually which notifications can stay in the action center.

**Comment by amt-work** [comment]
You unfortunately can't set these properties if you are trying to customize the notification with the template class. It would be nice to be able to provide options to the toast node as well to be able to change the duration and such of the notification. @felixrieseberg
